"""modificaciones

Revision ID: e59c552cec57
Revises: 63c11c692ff8
Create Date: 2026-03-31 22:29:17.508884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e59c552cec57'
down_revision = '63c11c692ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('quantity')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
