import os #ACCEDER A VARIABLES DEL SO
from dotenv import load_dotenv #IMPORTAR PARA CARGAR LAS VARIABLES DE ENTORNO

load_dotenv()

class Config:
    #base de datos
    SQLALCHEMY_DATABASE_URI = os.getenv(
        'DATABASE_URL'
    ) #CONEXION A LA BASE DE DATOS
    SQLALCHEMY_TRACK_MODIFICATIONS = False #DESACTIVAR EL SEGUIMIENTO DE MODIFICACIONES DE SQLALCHEMY