# Generated by Django 5.2.11 on 2026-04-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='created_at',
        ),
    ]
